-- 45_datetime.sql
-- DATE / TIMESTAMP 列与字面量、EXTRACT、INTERVAL 算术
--
-- 语义说明：
--   - DATE 字面量按 'YYYY-MM-DD' 解析；TIMESTAMP 按 'YYYY-MM-DD HH:MM:SS' 解析。
--   - DATE / TIMESTAMP 在底层持久化为 VARCHAR；运行时比较/算术在 ExpressionEvaluator
--     中以 epoch 秒为权威表示完成。
--   - INTERVAL <n> <unit>：DAY/HOUR/MINUTE/SECOND 是固定秒数；MONTH/YEAR 按日历月
--     月末做夹取（end-of-month clamping）。
--   - EXTRACT 返回 INT（SECOND 字段保留整数秒）。

CREATE TABLE t (id INT, d DATE, ts TIMESTAMP);
INSERT INTO t VALUES (1, DATE '2024-03-15', TIMESTAMP '2024-03-15 12:30:45');
INSERT INTO t VALUES (2, DATE '2025-01-01', TIMESTAMP '2025-01-01 00:00:00');

-- EXTRACT(YEAR/MONTH/DAY FROM DATE 列)
SELECT EXTRACT(YEAR FROM d), EXTRACT(MONTH FROM d), EXTRACT(DAY FROM d)
FROM t
ORDER BY id;

-- EXTRACT(HOUR/MINUTE FROM TIMESTAMP 列)
SELECT ts, EXTRACT(HOUR FROM ts), EXTRACT(MINUTE FROM ts)
FROM t
ORDER BY id;

-- DATE + INTERVAL '7' DAY
SELECT d + INTERVAL '7' DAY
FROM t
ORDER BY id;

-- TIMESTAMP - INTERVAL 1 HOUR
SELECT ts - INTERVAL 1 HOUR
FROM t
WHERE id = 1;

-- WHERE d > DATE '2024-06-01'
SELECT * FROM t WHERE d > DATE '2024-06-01';

-- WHERE ts < TIMESTAMP '2025-01-01 00:00:01'
SELECT * FROM t WHERE ts < TIMESTAMP '2025-01-01 00:00:01';

exit;
