-- 52_set_isolation.sql
-- SET TRANSACTION ISOLATION LEVEL ...：从 SQL 层设置会话默认隔离级别。
-- 本文件只放「必然成功」的语句，保证 run_all_tests 的 exit code = 0；
-- 非法级别的语法报错断言放在 storage_ut::TestSetIsolationStatement 里。

CREATE TABLE t(a INT);
INSERT INTO t VALUES (1), (2), (3);

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN;
SELECT a FROM t ORDER BY a;
COMMIT;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT COUNT(*) FROM t;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN;
INSERT INTO t VALUES (4);
ROLLBACK;

SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
BEGIN;
SELECT a FROM t ORDER BY a;
COMMIT;

SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
SELECT COUNT(*) FROM t;