-- 91_order_by_ordinal_cast_default.sql
-- 回归测试：ORDER BY <位置> / CAST AS 类型白名单扩展 / DEFAULT CURRENT_TIMESTAMP /
-- INSERT ... VALUES (..., DEFAULT) / INSERT ... DEFAULT VALUES。
--
-- 之前 4 个长期被忽视的边界现在都应正常工作。

-- ===== Bug 1: ORDER BY <ordinal> =====
CREATE TABLE ob(id INT, name VARCHAR);
INSERT INTO ob VALUES (3, 'c'), (1, 'a'), (2, 'b');

-- 1-based 列位置：DESC / ASC / 默认 ASC / 第 2 列
SELECT * FROM ob ORDER BY 1 DESC;
SELECT * FROM ob ORDER BY 1 ASC;
SELECT * FROM ob ORDER BY 1;
SELECT * FROM ob ORDER BY 2 DESC;
SELECT * FROM ob ORDER BY 2;

-- SELECT list 重排后 ORDER BY N 仍指向 select_list 位置
SELECT name, id FROM ob ORDER BY 1 DESC;
SELECT name, id FROM ob ORDER BY 2;

-- ORDER BY N 与表达式别名混用
SELECT id+1 AS x FROM ob ORDER BY 1;
SELECT id*10 AS scaled, id FROM ob ORDER BY 1 DESC;

-- UNION / ORDER BY 1（用左 SELECT 的 select_list 计数）
SELECT 1 AS a, 'x' AS b UNION SELECT 2, 'y' ORDER BY 1 DESC;

-- 越界报错
SELECT * FROM ob ORDER BY 99;

DROP TABLE ob;

-- ===== Bug 2: CAST AS 类型白名单 =====
CREATE TABLE c(id INT);
INSERT INTO c VALUES (42);

-- 之前全部被「expected type name after AS」拒绝；现在都能跑通。
SELECT CAST(id AS REAL)    FROM c;
SELECT CAST(id AS DOUBLE)  FROM c;
SELECT CAST(id AS DECIMAL) FROM c;
SELECT CAST(id AS NUMERIC) FROM c;
SELECT CAST(id AS CHAR)    FROM c;
SELECT CAST(id AS TEXT)    FROM c;
SELECT CAST(id AS BOOLEAN) FROM c;
SELECT CAST(id AS SMALLINT) FROM c;
SELECT CAST(id AS TINYINT) FROM c;
-- 旧的仍然支持
SELECT CAST(id AS INT)     FROM c;
SELECT CAST(id AS FLOAT)   FROM c;
SELECT CAST(id AS VARCHAR) FROM c;

-- CAST AS DATE / TIMESTAMP 在关键字白名单扩展之前报 "expected type name after AS"。
SELECT CAST('2024-01-15' AS DATE);
SELECT CAST(NOW() AS TIMESTAMP);
SELECT CAST('2024-01-15 12:30:00' AS TIMESTAMP);
SELECT CAST(id AS DATE), CAST(id AS TIMESTAMP) FROM c;

-- 原有的 DATE '...' / TIMESTAMP '...' 字面量语法仍可用（ParsePrimaryExpr 路径）
SELECT DATE '2024-01-15';
SELECT TIMESTAMP '2024-01-15 12:30:00';

-- CAST 类型带参数 —— DECIMAL(p,s) / NUMERIC(p,s) / VARCHAR(n) / CHAR(n)
-- 之前 `CAST(100 AS DECIMAL(10,2))` 在第二个整数处报
-- "expected ')' after CAST type parameter (got ',')"
SELECT CAST(100 AS DECIMAL(10,2));
SELECT CAST(100 AS DECIMAL(5));
SELECT CAST(100 AS DECIMAL);
SELECT CAST(100 AS NUMERIC(10,2));
SELECT CAST(100 AS NUMERIC(5));
SELECT CAST('hi' AS VARCHAR(20));
SELECT CAST('hi' AS CHAR(5));
-- 空参数列表 `()` 也合法
SELECT CAST(id AS DECIMAL());

DROP TABLE c;

-- ===== Bug 3: DEFAULT CURRENT_TIMESTAMP / DEFAULT NOW() =====
CREATE TABLE ct1(id INT, ts VARCHAR DEFAULT CURRENT_TIMESTAMP);
INSERT INTO ct1(id) VALUES (1);
SELECT * FROM ct1 WHERE id = 1;

CREATE TABLE ct2(id INT, ts VARCHAR DEFAULT NOW());
INSERT INTO ct2(id) VALUES (1);
SELECT * FROM ct2 WHERE id = 1;

-- val DEFAULT NOW() —— ALTER ADD COLUMN 路径
CREATE TABLE ct3(id INT);
ALTER TABLE ct3 ADD COLUMN created VARCHAR DEFAULT NOW();
INSERT INTO ct3(id) VALUES (1);
SELECT * FROM ct3 WHERE id = 1;

DROP TABLE ct1;
DROP TABLE ct2;
DROP TABLE ct3;

-- ===== Bug 4a: INSERT ... VALUES (..., DEFAULT) =====
CREATE TABLE vt(id INT, name VARCHAR DEFAULT 'unnamed', score INT DEFAULT 0);
-- 部分列省略（VALUES 列表里写 DEFAULT）：
INSERT INTO vt(id, name) VALUES (1, DEFAULT);
-- 不同位置上的 DEFAULT：
INSERT INTO vt(id, name, score) VALUES (2, 'bob', DEFAULT);
INSERT INTO vt(id, score) VALUES (3, DEFAULT);
-- 列名列表外允许 DEFAULT —— 隐式列位置上写 DEFAULT：
CREATE TABLE vt2(a INT DEFAULT 7, b INT);
INSERT INTO vt2 VALUES (DEFAULT, 9);
-- 列上没有 DEFAULT 表达式 → NULL
CREATE TABLE vt3(id INT, name VARCHAR);
INSERT INTO vt3(id, name) VALUES (1, DEFAULT);

SELECT * FROM vt ORDER BY id;
SELECT * FROM vt2;
SELECT * FROM vt3;

-- DEFAULT(col) 函数调用形式 —— 等价于裸 DEFAULT（用同列默认）
CREATE TABLE vt4(id INT, name VARCHAR DEFAULT 'unnamed');
INSERT INTO vt4(id, name) VALUES (1, DEFAULT(name));
SELECT * FROM vt4;

-- DEFAULT(col) 跨列 —— 取 col 的默认而非当前位置列
CREATE TABLE vt5(id INT, name VARCHAR DEFAULT 'auto', score INT DEFAULT 100);
INSERT INTO vt5(id, name, score) VALUES (1, DEFAULT(score), DEFAULT(name));
SELECT * FROM vt5;

-- DEFAULT(col) 引用不存在的列 → 报错
CREATE TABLE vt6(id INT, name VARCHAR DEFAULT 'auto');
INSERT INTO vt6(id, name) VALUES (1, DEFAULT(missing));

DROP TABLE vt;
DROP TABLE vt2;
DROP TABLE vt3;
DROP TABLE vt4;
DROP TABLE vt5;
DROP TABLE vt6;

-- ===== Bug 4b: INSERT ... DEFAULT VALUES =====
CREATE TABLE dv(id INT, name VARCHAR DEFAULT 'auto', score INT DEFAULT 99);
INSERT INTO dv DEFAULT VALUES;
SELECT * FROM dv;

-- DEFAULT VALUES 不能带列名列表（标准约束）
INSERT INTO dv(id) DEFAULT VALUES;

DROP TABLE dv;

-- ===== 综合：ORDER BY 位置 + 默认值同表 =====
CREATE TABLE mix(id INT, ts VARCHAR DEFAULT CURRENT_TIMESTAMP);
INSERT INTO mix(id) VALUES (1);
INSERT INTO mix(id) VALUES (2);
INSERT INTO mix(id) VALUES (3);
SELECT * FROM mix ORDER BY 1 DESC;
SELECT * FROM mix ORDER BY 2;

DROP TABLE mix;

exit;
